name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🚀 Checkout code
      uses: actions/checkout@v3

    - name: 📤 Deploy to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.WHM_HOST }}
        username: ${{ secrets.WHM_USERNAME }}
        key: ${{ secrets.WHM_SSH_KEY }}
        source: "*"
        target: "/home/nuyouukcom/public_html"
        rm: false

    - name: 🔒 Set correct permissions
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.WHM_HOST }}
        username: ${{ secrets.WHM_USERNAME }}
        key: ${{ secrets.WHM_SSH_KEY }}
        script: |
          # Set ownership
          chown -R nuyouukcom:nuyouukcom /home/nuyouukcom/public_html

          # Set directory permissions
          find /home/nuyouukcom/public_html -type d -exec chmod 755 {} \;

          # Set file permissions
          find /home/nuyouukcom/public_html -type f -exec chmod 644 {} \;

          # Make uploads writable
          [ -d "/home/nuyouukcom/public_html/assets/images/uploads" ] && \
            chmod 777 /home/nuyouukcom/public_html/assets/images/uploads

          # Protect .env
          [ -f "/home/nuyouukcom/public_html/.env" ] && \
            chmod 600 /home/nuyouukcom/public_html/.env